### ISSUE TITLE
An interval of less than 200ms can create performance issues: remove and/or explain

### ISSUE THREAD

**Issue by dobriai** [shaunpersad/throttled-queue#12]
There is a warning, in there:
```
if (interval &lt; 200) {
   console.warn('An interval of less than 200ms can create performance issues.');
}
```
which leads to the following questions/requests:

- What is this based on? What is so special about 200ms?
- If this really needs to be there, can you elaborate in the README file? The warning can be easily missed. It is also unclear why it is there.
- I would like an option to suppress it, please! Or just remove that if-block and warn in the README file instead :-)

Thanks!

**Comment by shaunpersad** [comment]
Back when I made this 5 years ago, browsers would have a very difficult time with any intervals < 200ms. Today's browsers seem much more capable of handling it, so I've now removed that warning in v2.
