### ISSUE TITLE
execution never ends

### ISSUE THREAD

**Issue by terchris** [shaunpersad/throttled-queue#3]
I'm using throttled-queue to limit updates to my CKAN.org based server.

This works fine and my script loops and put all axios calls to the queue.
My CKAN server is happy and all is fine. Except that execution does not end when the queue is empty.

Debugging in vscode and when i pause execution the code always stop at 
const fn = function(asyncId) in function emitHookFactory.
I see that a variable asyncId is doing come counting.

I want my node script to end its execution when the queue is empty. How can I do this ?

**Comment by hlalani** [comment]
I have the same problem - I'd like to know when the execution is done so that I can exit the node process.
